### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by manageC0d** [MiladSadeghi/fake-identity-generator#1]
this is not working. Can we create a Turkish ID?
sample:https://upload.wikimedia.org/wikipedia/commons/c/c0/TR_Nat_ID_Card_Front.png

**Comment by MiladSadeghi** [comment]
@manageC0d  Thanks for your report. Yes, I am aware of this problem. You must use the Cors Unblock plugin. But I'm fixing this problem.

**Comment by manageC0d** [comment]
thank you. Will you come back when I fix it, I want to use it.
Also, it will be like this, right?
https://upload.wikimedia.org/wikipedia/commons/c/c0/TR_Nat_ID_Card_Front.png

**Comment by MiladSadeghi** [comment]
@manageC0d The project is working now. There was a problem with the cors policy from the api. But that's not what you think! The photo you are talking about is a fake identity card and an illegal act! Sorry I can not help you.
